language: node_js
sudo: enabled
node_js:
  - "8"
before_script:
  - npm i pcreate
  - ls node_modules/pcreate/node_modules
script:
  - npm run test
  - npm run build2
after_script:
  - npm run test-nyc

cache:
  directories:
  - node_modules

deploy:
  - provider: npm
    skip_cleanup: true
    email: heifade@126.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      repo: heifade/zip-i
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master

